### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by leesser** [1826888766/read-book-status-bar#11]
- Issue Type: `Performance`
- Extension Name: `read-book-status-bar`
- Extension Version: `1.0.5`
- OS Version: `Windows_NT x64 10.0.19041`
- VSCode version: `1.54.3`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`c:\Users\DELL\AppData\Local\Temp\read-book.read-book-status-bar-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by 1826888766** [comment]
> * 问题类型：`Performance`
> * 扩展名称：`read-book-status-bar`
> * 扩展版本：`1.0.5`
> * 操作系统版本：`Windows_NT x64 10.0.19041`
> * VS代码版本：`1.54.3`
> 
> ⚠️请务必从您的_家庭_目录**中附加**此文件 -
> 目录：⚠️`c:\Users\DELL\AppData\Local\Temp\read-book.read-book-status-bar-unresponsive.cpuprofile.txt`
> 
> 在此处查找更多详细信息[：https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load](https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load)
我会尽快解决此问题
感谢反馈

**Comment by 1826888766** [comment]
> * 问题类型：`Performance`
> * 扩展名称：`read-book-status-bar`
> * 扩展版本：`1.0.5`
> * 操作系统版本：`Windows_NT x64 10.0.19041`
> * VS代码版本：`1.54.3`
> 
> ⚠️请务必从您的_家庭_目录**中附加**此文件 -
> 目录：⚠️`c:\Users\DELL\AppData\Local\Temp\read-book.read-book-status-bar-unresponsive.cpuprofile.txt`
> 
> 在此处查找更多详细信息[：https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load](https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load)

感谢反馈，我会尽快解决

**Comment by 1826888766** [comment]
> * Issue Type: `Performance`
> * Extension Name: `read-book-status-bar`
> * Extension Version: `1.0.5`
> * OS Version: `Windows_NT x64 10.0.19041`
> * VSCode version: `1.54.3`
> 
> ⚠️ Make sure to **attach** this file from your _home_-directory:
> ⚠️`c:\Users\DELL\AppData\Local\Temp\read-book.read-book-status-bar-unresponsive.cpuprofile.txt`
> 
> Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

可以加我qq 1826888766 把那个文件发我 `c:\Users\DELL\AppData\Local\Temp\read-book.read-book-status-bar-unresponsive.cpuprofile.txt`
