### ISSUE TITLE
导入的书籍无法删除

### ISSUE THREAD

**Issue by leesser** [1826888766/read-book-status-bar#12]
导入的书籍无法删除

**Comment by 1826888766** [comment]
> 导入的书籍无法删除

导入的书籍会存储在本地的sqlite数据库中，可以链接这个数据库进行修改，文件位置在vscode安装目录，.db后缀的文件，目前没有增加删除数据功能

**Comment by CloudyBao** [comment]
找不到这个.db文件

**Comment by 1826888766** [comment]
> 找不到这个.db文件

在vscode的安装目录
