### ISSUE TITLE
无法获取目录

### ISSUE THREAD

**Issue by shuyudao** [1826888766/read-book-status-bar#13]
我下载了几本txt，但是导入后，都无法获取目录，一直显示正在获取目录

**Comment by 1826888766** [comment]
可以加我qq 1826888766把txt发我一下

**Comment by shuyudao** [comment]
> 可以加我qq 1826888766把txt发我一下

https://www.5200wxw.com/modules/article/txtarticle.php?id=13908&fname=%B5%DA%D2%BB%D0%F2%C1%D0(5200%CE%C4%D1%A7%CD%F8%20www.5200wxw.com).txt

**Comment by 1826888766** [comment]
在配置中有断章正则配置，默认的是`(\\s|\\n)(第)([\\u4e00-\\u9fa5a-zA-Z0-9]{1,7})[章][^\\n]{1,35}(|\\n)` 不太符合你的文章
