### ISSUE TITLE
3.5M大小的txt文件获取目录时间过长

### ISSUE THREAD

**Issue by yanghuanrong** [1826888766/read-book-status-bar#14]
以为程序卡死了

**Comment by 1826888766** [comment]
> 以为程序卡死了

这个导入的操作并不是只导入目录，是吧文件的所有内容导入到sqlite数据库，写入时间有点长，

**Comment by yanghuanrong** [comment]
这个写入确实很长。十多分钟了。毫无反应。期待作者可以加入进度条这种反馈

**Comment by 1826888766** [comment]
> 这个写入确实很长。十多分钟了。毫无反应。期待作者可以加入进度条这种反馈

十多分钟的情况应该是有问题，可以把文件发给我吗？qq: 1826888766

**Comment by BGFGB** [comment]
遇到同样的问题了，请问有结果了吗？

**Comment by yanghuanrong** [comment]
> 遇到同样的问题了，请问有结果了吗？

试试修改一下编码。好像和文件编码有关系

**Comment by BGFGB** [comment]
> > 遇到同样的问题了，请问有结果了吗？
> 
> 试试修改一下编码。好像和文件编码有关系

文件是utf-8的，能说一下目前支持哪些编码吗？

**Comment by 1826888766** [comment]
可以用vscode先打开一次再以utf8保存

**Comment by 1826888766** [comment]
插件已升级，可以尝试使用新版插件
