### ISSUE TITLE
个别篇章目录标题排序出现错乱

### ISSUE THREAD

**Issue by yanghuanrong** [1826888766/read-book-status-bar#15]
![微信截图_20210727092308](https://user-images.githubusercontent.com/18067120/127080140-73b376a1-06fc-4c26-a198-8bd12bb800f9.png)
不知道这个排序规则是按照什么来的。

**Comment by 1826888766** [comment]
保存目录的时候不是同步的，有可能是循环异步造成的，之后优化一下

**Comment by yanghuanrong** [comment]
期待作者更新

**Comment by 1826888766** [comment]
> ![微信截图_20210727092308](https://user-images.githubusercontent.com/18067120/127080140-73b376a1-06fc-4c26-a198-8bd12bb800f9.png)
> 不知道这个排序规则是按照什么来的。

可以尝试一下重新导入，如果还是这个问题，同样的排名，有可能是读取的问题
