### ISSUE TITLE
笔趣阁书源“失效”

### ISSUE THREAD

**Issue by novolife** [1826888766/read-book-status-bar#16]
大抵是要科学才能上了，但是科学上网了还是搜索不到小说。

**Comment by 1826888766** [comment]
笔趣阁域名又换了，我一会重新发布一个

**Comment by 1826888766** [comment]
> 大抵是要科学才能上了，但是科学上网了还是搜索不到小说。

不需要，笔趣阁域名又换了

**Comment by 1826888766** [comment]
> 大抵是要科学才能上了，但是科学上网了还是搜索不到小说。

但是目前这个域名还是可以搜索的，你的搜索书名是什么？

**Comment by novolife** [comment]
> 但是目前这个域名还是可以搜索的，你的搜索书名是什么？

搜了临高启明但是没结果哇，我在那个域名搜了一下是有收录的，是不是搜索结果返回比较玄学？这网站收录的书好像也不够全，还是建议换一个。

**Comment by 1826888766** [comment]
> > 但是目前这个域名还是可以搜索的，你的搜索书名是什么？
> 
> 搜了临高启明但是没结果哇，我在那个域名搜了一下是有收录的，是不是搜索结果返回比较玄学？这网站收录的书好像也不够全，还是建议换一个。

是有收入的，只不过只有一本书的情况会不进入列表页，很难受，今天有时间我更新一下，增加导入书籍 网络地址功能

**Comment by 1826888766** [comment]
> > 但是目前这个域名还是可以搜索的，你的搜索书名是什么？
> 
> 搜了临高启明但是没结果哇，我在那个域名搜了一下是有收录的，是不是搜索结果返回比较玄学？这网站收录的书好像也不够全，还是建议换一个。

你也可以搜索 `启明`，列表第三个就是

**Comment by 1826888766** [comment]
> > 但是目前这个域名还是可以搜索的，你的搜索书名是什么？
> 
> 搜了临高启明但是没结果哇，我在那个域名搜了一下是有收录的，是不是搜索结果返回比较玄学？这网站收录的书好像也不够全，还是建议换一个。

在设置中 扩展设置里 `状态栏读书` 的设置 可以切换平台 目前支持三个，
