### ISSUE TITLE
用句号断行影响阅读体验

### ISSUE THREAD

**Issue by novolife** [1826888766/read-book-status-bar#17]
导入了一本本地的小说，阅读时发现行末都没有符号，而且会把一个括号内的内容断开来。
![无标题](https://user-images.githubusercontent.com/43333869/131065431-8d13407c-918e-4f62-b26a-b579037b2da5.png)
对比原文发现，此处应为句号，但句号却变成了换行符。
![无标题](https://user-images.githubusercontent.com/43333869/131065569-3d8c3a68-e5e4-45f6-ae08-bf359a6f559f.png)
在设置里没找到断行通配符的设置，姑且认为是插件会自动地把句号替换成换行。

**Comment by 1826888766** [comment]
> 导入了一本本地的小说，阅读时发现行末都没有符号，而且会把一个括号内的内容断开来。
> ![无标题](https://user-images.githubusercontent.com/43333869/131065431-8d13407c-918e-4f62-b26a-b579037b2da5.png)
> 对比原文发现，此处应为句号，但句号却变成了换行符。
> ![无标题](https://user-images.githubusercontent.com/43333869/131065569-3d8c3a68-e5e4-45f6-ae08-bf359a6f559f.png)
> 在设置里没找到断行通配符的设置，姑且认为是插件会自动地把句号替换成换行。

是的，目前的断句正则是这么实现的，有时间我把断句正则也改为可配置项
