### ISSUE TITLE
切换平台

### ISSUE THREAD

**Issue by badguyp** [1826888766/read-book-status-bar#18]
这没法切换平台啊只能笔趣阁搜索,是我的操作失误吗

**Comment by 1826888766** [comment]
在设置中修改

**Comment by badguyp** [comment]
![image](https://user-images.githubusercontent.com/57091435/143667327-73297c75-0ca3-49b3-9030-427f7ea68737.png)
差一点我就改源代码了哈哈,感谢感谢

**Comment by badguyp** [comment]
![image](https://user-images.githubusercontent.com/57091435/143671106-6af15966-5ddf-4e32-83ff-4b41b78f5a5d.png)
报错了
这是啥错啊
