### ISSUE TITLE
作者你好，能再改一下不？如下 

### ISSUE THREAD

**Issue by jingj5** [1826888766/read-book-status-bar#2]
因为有时候，一行太长了，状态栏显示不完，所以能否再加上一个快捷键，点击之后，显示当前位置+（配置中，状态栏显示文字数目），也就是下一串文字，而不是下一行。
嘿嘿，先谢谢了。

**Comment by 1826888766** [comment]
配置里有配置每一行的字数，超出的会截取作为下一行显示

**Comment by 1826888766** [comment]
![image](https://user-images.githubusercontent.com/31725579/98779779-4420df80-242f-11eb-8b32-18020c00e308.png)

**Comment by jingj5** [comment]
我试了这个配置，当我用下一行快捷键时，它读取的是整个一行，这样就会字数显示不完全，如图。

![1](https://user-images.githubusercontent.com/5019232/98800391-48f38c80-244b-11eb-911f-b7e69789ed50.jpg)
![2](https://user-images.githubusercontent.com/5019232/98800392-4a24b980-244b-11eb-9d88-48cc271c3fce.jpg)
![3](https://user-images.githubusercontent.com/5019232/98800394-4a24b980-244b-11eb-83e5-0745bc859d03.jpg)

**Comment by 1826888766** [comment]
感谢反馈，我晚上测试修改一下

**Comment by 1826888766** [comment]
已修复

**Comment by jingj5** [comment]
完美

**Comment by 1826888766** [comment]
> 完美

还有其他想法尽管提
