### ISSUE TITLE
2.0.9版本问题

### ISSUE THREAD

**Issue by chenlongcheck** [1826888766/read-book-status-bar#23]
目前添加入目录后，再次的打开VScode需要再次添加书籍
![Dingtalk_20220811094421](https://user-images.githubusercontent.com/43593288/184051099-b37c2f14-0297-456a-b44b-b75197f75aad.jpg)
开始阅读出现以上错误，且无法自动下一行，需要在设置里面开/关一下自动阅读才行

**Comment by 1826888766** [comment]
> 目前添加入目录后，再次的打开VScode需要再次添加书籍 ![Dingtalk_20220811094421](https://user-images.githubusercontent.com/43593288/184051099-b37c2f14-0297-456a-b44b-b75197f75aad.jpg) 开始阅读出现以上错误，且无法自动下一行，需要在设置里面开/关一下自动阅读才行

书籍获取不到目录吗？还是书架没有这本书了

**Comment by 1826888766** [comment]
> 



> 目前添加入目录后，再次的打开VScode需要再次添加书籍 ![Dingtalk_20220811094421](https://user-images.githubusercontent.com/43593288/184051099-b37c2f14-0297-456a-b44b-b75197f75aad.jpg) 开始阅读出现以上错误，且无法自动下一行，需要在设置里面开/关一下自动阅读才行

qq群 755708694

**Comment by chenlongcheck** [comment]
没有这本书，且下一章错误，现在阅读的是100章，自动/手动下一章都会跳转到第一章开始，
