### ISSUE TITLE
2.0.9 BUG

### ISSUE THREAD

**Issue by jinhuiyon** [1826888766/read-book-status-bar#24]
1、点击目录阅读后再点击书架阅读  章节名丢失
![1660184671183](https://user-images.githubusercontent.com/48462153/184055086-8a96d4fb-3a36-45f9-939b-7d2c4ba70f39.jpg)

2、阅读换行上一行的内容会跑到下一行
![1660184747252](https://user-images.githubusercontent.com/48462153/184055292-31988d87-765c-44f3-9926-aff5bc034c90.jpg)
![1660184761654](https://user-images.githubusercontent.com/48462153/184055329-a3ecd704-f815-47f4-9331-aeeba9f3fa3f.jpg)

3、自动跳转下一章会跳转到第一章，手动跳转正常

**Comment by 1826888766** [comment]
已修复，

**Comment by 1826888766** [comment]
> 1、点击目录阅读后再点击书架阅读 章节名丢失 ![1660184671183](https://user-images.githubusercontent.com/48462153/184055086-8a96d4fb-3a36-45f9-939b-7d2c4ba70f39.jpg)
> 
> 2、阅读换行上一行的内容会跑到下一行 ![1660184747252](https://user-images.githubusercontent.com/48462153/184055292-31988d87-765c-44f3-9926-aff5bc034c90.jpg) ![1660184761654](https://user-images.githubusercontent.com/48462153/184055329-a3ecd704-f815-47f4-9331-aeeba9f3fa3f.jpg)
> 
> 3、自动跳转下一章会跳转到第一章，手动跳转正常

请升级2.0.10

**Comment by jinhuiyon** [comment]
1可以了  2 3还是有问题

**Comment by 1826888766** [comment]
> 1可以了 2 3还是有问题

换行问题修复了，自动跳转到第一章，暂时没有发现这个问题

**Comment by 1826888766** [comment]
> 1可以了 2 3还是有问题

可以升级到2.0.12试一试

**Comment by jinhuiyon** [comment]
换行没问题了   2.0.13点击下一章目录没有已读勾选

**Comment by 1826888766** [comment]
> 换行没问题了 2.0.13点击下一章目录没有已读勾选

我试了没问题，你那是哪本书，或者删除重新加入书架试试？

**Comment by jinhuiyon** [comment]
最新版本  点目录的阅读有  点右下角的下一章没有已读
![1660209498813](https://user-images.githubusercontent.com/48462153/184102310-ad84b0a5-d337-4297-9796-78e2c218920c.jpg)

**Comment by jinhuiyon** [comment]
应该不是书的问题  我换了好几本书试了都一样

**Comment by chenlongcheck** [comment]
> 换行没问题了 2.0.13点击下一章目录没有已读勾选

没有勾选应该是要管理员模式启动，之前的版本也是这样
在2.0.14下，我的书架无法保存，每次关闭编辑器后都会丢失，你那儿是否有这情况

**Comment by 1826888766** [comment]
> > 换行没问题了 2.0.13点击下一章目录没有已读勾选
> 
> 没有勾选应该是要管理员模式启动，之前的版本也是这样 在2.0.14下，我的书架无法保存，每次关闭编辑器后都会丢失，你那儿是否有这情况

没有发现这个问题，我重启电脑也不会丢失，你的是什么系统

**Comment by chenlongcheck** [comment]
> > > 换行没问题了 2.0.13点击下一章目录没有已读勾选
> > 
> > 
> > 没有勾选应该是要管理员模式启动，之前的版本也是这样 在2.0.14下，我的书架无法保存，每次关闭编辑器后都会丢失，你那儿是否有这情况
> 
> 没有发现这个问题，我重启电脑也不会丢失，你的是什么系统

Windows10的系统

**Comment by 1826888766** [comment]
现在这个存储用的vscode提供的globalState,我看看加一个文件存储的方式，不太清楚你的是什么原因

**Comment by chenlongcheck** [comment]
> 现在这个存储用的vscode提供的globalState,我看看加一个文件存储的方式，不太清楚你的是什么原因

2.0.15还是如此，每次打开有这个错误：Cannot read properties of undefined (reading 'forEach')
且每次都需要开关‘是否阅读下一行功能才能自动阅读’
这是我的vscode版本
版本: 1.70.1 (system setup)
日期: 2022-08-10T06:08:33.642Z
Electron: 18.3.5
Chromium: 100.0.4896.160
Node.js: 16.13.2
V8: 10.0.139.17-electron.0
OS: Windows_NT x64 10.0.19044

**Comment by 1826888766** [comment]
这个有可能是获取书架数据时返回了null，所以报这个错

**Comment by 1826888766** [comment]
> > 现在这个存储用的vscode提供的globalState,我看看加一个文件存储的方式，不太清楚你的是什么原因
> 
> 2.0.15还是如此，每次打开有这个错误：Cannot read properties of undefined (reading 'forEach') 且每次都需要开关‘是否阅读下一行功能才能自动阅读’ 这是我的vscode版本 版本: 1.70.1 (system setup) 日期: 2022-08-10T06:08:33.642Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

vscode 默认的存储路径时 `C:\Users\{你的用户名}\AppData\Roaming\Code\User\globalStorage` ,这个是不是vscode自动删除了

**Comment by 1826888766** [comment]
> > 现在这个存储用的vscode提供的globalState,我看看加一个文件存储的方式，不太清楚你的是什么原因
> 
> 2.0.15还是如此，每次打开有这个错误：Cannot read properties of undefined (reading 'forEach') 且每次都需要开关‘是否阅读下一行功能才能自动阅读’ 这是我的vscode版本 版本: 1.70.1 (system setup) 日期: 2022-08-10T06:08:33.642Z Electron: 18.3.5 Chromium: 100.0.4896.160 Node.js: 16.13.2 V8: 10.0.139.17-electron.0 OS: Windows_NT x64 10.0.19044

这个报错问题我处理了，但是这个存储的问题还没想到怎么解决
