### ISSUE TITLE
阅读bug

### ISSUE THREAD

**Issue by onlytheworld** [1826888766/read-book-status-bar#27]
[该文件](https://github.com/1826888766/read-book-status-bar/blob/5e6fd542afd086161731b0bd95dd7f9013560ccb/src/commands/Read.ts#L208)存在bug
<img width="392" alt="image" src="https://user-images.githubusercontent.com/37205103/220004195-5ac9bf8b-ba2f-4378-9779-002ed0c9c73e.png">
在这里的else语句应该加入`newContents.push(pre.trim());`否则会丢失最后一小段文本内容

**Comment by 1826888766** [comment]
好的，我看一下



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年2月20日(星期一) 中午11:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: [1826888766/read-book-status-bar] 阅读bug (Issue #27)





 
该文件存在bug
 
 在这里的else语句应该加入newContents.push(pre.trim());否则会丢失最后一小段文本内容

**Comment by 1826888766** [comment]
> 

这个问题修复了，是因为最后一行文字超出设定的字符限制后，会进行下一行但这时没有下一行了，所以应该判断一下`pre`是否有内容，插入到新的列表即可
