### ISSUE TITLE
一行会出现展示不完的情况

### ISSUE THREAD

**Issue by gaomengzhou** [1826888766/read-book-status-bar#4]
一行会出现展示不完的情况

**Comment by 1826888766** [comment]
这个问题已经修复过了，你的还会出先吗？你设置的每行显示多少字数呢

**Comment by gaomengzhou** [comment]
> 这个问题已经修复过了，你的还会出先吗？你设置的每行显示多少字数呢

我直接写的200. 应该是最大了.好像100就满了

搜的是大罗大陆4 小说. 会出现这个情况

**Comment by 1826888766** [comment]
有的句子没有标点符号句号，分割不了，建议设置为40-80之间
