### ISSUE TITLE
可以仿造thiefBook弄个老板键, 一按就隐藏,或者随机显示什么语言的 hello world

### ISSUE THREAD

**Issue by gaomengzhou** [1826888766/read-book-status-bar#5]
有时候离开去上厕所有点不放心 怕被发现哈哈.

**Comment by 1826888766** [comment]
感谢提出的建议，稍后更新

**Comment by gaomengzhou** [comment]
> 感谢提出的建议，稍后更新

还有就是有的小说几千个章节, 有没有什么办法快速翻到后面的章节. 
 其他的几乎完美了.

**Comment by 1826888766** [comment]
可以，感谢建议

**Comment by 1826888766** [comment]
> > 感谢提出的建议，稍后更新
> 
> 还有就是有的小说几千个章节, 有没有什么办法快速翻到后面的章节.
> 其他的几乎完美了.

已更新
