### ISSUE TITLE
插件之主，我又来了，能否加入这个功能，导入本地txt文件

### ISSUE THREAD

**Issue by jingj5** [1826888766/read-book-status-bar#6]
如题，导入本地txt小说，用来阅读。抱拳。

**Comment by 1826888766** [comment]
可以，下次更新

**Comment by 1826888766** [comment]
> 如题，导入本地txt小说，用来阅读。抱拳。
已更新，本次更新引入sqlite数据库，更新时间加长，只支持txt导入，可自定义断章规则，具体查看配置，使用导入功能需要切换配置 `阅读平台` 为 `file`，右下角点击+号图标选择文件导入
