### ISSUE TITLE
大佬，提一个BUG，关于文字拆分的

### ISSUE THREAD

**Issue by jingj5** [1826888766/read-book-status-bar#7]
1. 图1是小说的原文
2. 图2是vscode里面的第一节文字
3. 图3是vscode里面的第二节文字
4. 图4是vscode里面的下一段文字的开头
图3到图4之间少了上一段的最后一节文字，麻烦大佬看一下，祝元旦快乐！
![1](https://user-images.githubusercontent.com/5019232/103391078-87a3ea00-4b52-11eb-9b27-b58ac23b74db.png)
![2](https://user-images.githubusercontent.com/5019232/103391083-8b377100-4b52-11eb-9fd5-d38b70b06258.png)
![3](https://user-images.githubusercontent.com/5019232/103391084-8e326180-4b52-11eb-8d4e-923421f0eaed.png)
![4](https://user-images.githubusercontent.com/5019232/103391085-8ffc2500-4b52-11eb-9c52-602c7eb14692.png)

**Comment by 1826888766** [comment]
> 1. 图1是小说的原文
> 2. 图2是vscode里面的第一节文字
> 3. 图3是vscode里面的第二节文字
> 4. 图4是vscode里面的下一段文字的开头
>    图3到图4之间少了上一段的最后一节文字，麻烦大佬看一下，祝元旦快乐！
>    ![1](https://user-images.githubusercontent.com/5019232/103391078-87a3ea00-4b52-11eb-9b27-b58ac23b74db.png)
>    ![2](https://user-images.githubusercontent.com/5019232/103391083-8b377100-4b52-11eb-9fd5-d38b70b06258.png)
>    ![3](https://user-images.githubusercontent.com/5019232/103391084-8e326180-4b52-11eb-8d4e-923421f0eaed.png)
>    ![4](https://user-images.githubusercontent.com/5019232/103391085-8ffc2500-4b52-11eb-9c52-602c7eb14692.png)

感谢反馈，预计今天修复

**Comment by 1826888766** [comment]
> 1. 图1是小说的原文
> 2. 图2是vscode里面的第一节文字
> 3. 图3是vscode里面的第二节文字
> 4. 图4是vscode里面的下一段文字的开头
>    图3到图4之间少了上一段的最后一节文字，麻烦大佬看一下，祝元旦快乐！
>    ![1](https://user-images.githubusercontent.com/5019232/103391078-87a3ea00-4b52-11eb-9b27-b58ac23b74db.png)
>    ![2](https://user-images.githubusercontent.com/5019232/103391083-8b377100-4b52-11eb-9fd5-d38b70b06258.png)
>    ![3](https://user-images.githubusercontent.com/5019232/103391084-8e326180-4b52-11eb-8d4e-923421f0eaed.png)
>    ![4](https://user-images.githubusercontent.com/5019232/103391085-8ffc2500-4b52-11eb-9c52-602c7eb14692.png)

可以将你的小说文件的这一章发给我吗？1826888766@qq.com

**Comment by jingj5** [comment]
诡秘之主，哪一章不知道了。。。因为没有章节显示，很多地方都有，你试一试。

**Comment by 1826888766** [comment]
> 诡秘之主，哪一章不知道了。。。因为没有章节显示，很多地方都有，你试一试。

我复制了你的那段话，是正常，是不是有无法识别的换行，如果是因为段落分割问题，可以修改配置文件的分割正则

**Comment by jingj5** [comment]
看了下代码，是这里的一行注释掉就好了。
![Uploading kkk.png…]()

**Comment by 1826888766** [comment]
好的，我稍后发布一个新版本，

**Comment by 1826888766** [comment]
> 看了下代码，是这里的一行注释掉就好了。
> ![kkk](https://user-images.githubusercontent.com/5019232/103629692-9c7de480-4f7b-11eb-9ca0-f174f63876c2.png)

感谢指正

**Comment by jingj5** [comment]
收到，感谢！
