### ISSUE TITLE
一念永恒用笔趣阁搜不到，用起点获取目录一直不动，怎么搞？

### ISSUE THREAD

**Issue by caim18340** [1826888766/read-book-status-bar#8]

**Comment by 1826888766** [comment]
我看一下是不是他们的地址换了

**Comment by 1826888766** [comment]
> _No description provided._

这个问题是因为笔趣阁搜索的结果重定向了，获取不到内容，
你可以尝试手动复制书籍地址，点击目录即可

**Comment by 1826888766** [comment]
> _No description provided._

![image](https://user-images.githubusercontent.com/31725579/107015738-12be7280-67d8-11eb-980b-97a15c4ce253.png)

**Comment by 1826888766** [comment]
> _No description provided._

https://www.xbiquge.cc/book/630/

**Comment by caim18340** [comment]
设置里的路径和书名怎么保存的，复制后，点击获取目录就设置里就自动变成上次看的小说目录了

**Comment by 1826888766** [comment]
> 设置里的路径和书名怎么保存的，复制后，点击获取目录就设置里就自动变成上次看的小说目录了

手动设置需要重启一下，
起点的获取不到是因为他那个书籍不知为什么是异步加载的，爬不到内容

**Comment by 1826888766** [comment]
> 设置里的路径和书名怎么保存的，复制后，点击获取目录就设置里就自动变成上次看的小说目录了

![image](https://user-images.githubusercontent.com/31725579/107018524-82822c80-67db-11eb-87eb-2a631c6a39d8.png)

**Comment by 1826888766** [comment]
> 设置里的路径和书名怎么保存的，复制后，点击获取目录就设置里就自动变成上次看的小说目录了

解决了吗？

**Comment by caim18340** [comment]
解决了

**Comment by caim18340** [comment]
https://book.qidian.com/info/1979049#Catalog
起点的赘婿小说状态栏一直显示正在获取书籍目录信息，卡住了，看不了，重新加载也不行，起点资源里的

**Comment by 1826888766** [comment]
> https://book.qidian.com/info/1979049#Catalog
> 起点的赘婿小说状态栏一直显示正在获取书籍目录信息，卡住了，看不了，重新加载也不行，起点资源里的

很抱歉，对异步加载的小说页面暂时没有时间完成，目前正在重写这个项目，已完成80%，感谢你的支持，预计这周完成重写任务
